version: "3.8"
services:
  postgres:
    container_name: c-booking-postgres
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=c-booking-user
      - POSTGRES_PASSWORD=S3cr3tP4ssw0rd
      - POSTGRES_DB=c-booking
    volumes:
      - ./docker/postgres/db/data:/var/lib/postgresql/data
