services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: node_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
