services:
  # PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: node_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js (Express) service
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql://postgres:123@db:5432//node_example
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/usr/src/app

volumes:
  postgres_data:
